/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.Controlador;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.LayoutManager;
import java.awt.RenderingHints;
import java.awt.geom.RoundRectangle2D;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;


public class MenuPrincipal extends javax.swing.JFrame {

    private Controlador Controlador;
    private TomarPedidos TomarPedidos;
    public Cocina cocina;
    public FinDelDia FinDelDia;

    /**
     * Creates new form MenuPrincipal
     */
    int xMouse, yMouse;
    public MenuPrincipal() throws IOException {
        Controlador = new Controlador();
        cocina = new Cocina(Controlador);
        TomarPedidos = new TomarPedidos(Controlador, cocina);
        FinDelDia = new FinDelDia(Controlador);
        
        initComponents();
        setShape(new RoundRectangle2D.Double(0,0,getWidth(),getHeight(),25,25));
        b1.setBackground(new Color(0,0,0,0));
        b2.setBackground(new Color(0,0,0,0));
        b3.setBackground(new Color(0,0,0,0));
        this.setLocationRelativeTo(null);                                       //Centrar la ventana
        setIconImage(new ImageIcon(getClass().getResource("/Imagenes/icon.png")).getImage());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        CamareroButton = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        head = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        title1 = new javax.swing.JLabel();
        tx1 = new javax.swing.JLabel();
        b1 = new RoundedPanel(300,new Color(255,93,86));
        tx2 = new javax.swing.JLabel();
        b2 = new RoundedPanel(300,Color.yellow);
        tx3 = new javax.swing.JLabel();
        b3 = new RoundedPanel(300,new Color(28,191,48));
        dark = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        bgc = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 255, 153));
        setMinimumSize(new java.awt.Dimension(440, 580));
        setUndecorated(true);
        setResizable(false);
        setSize(new java.awt.Dimension(1080, 720));

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(140, 22, 25));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setBackground(new java.awt.Color(51, 56, 59));
        jButton2.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ic2.png"))); // NOI18N
        jButton2.setText("      Cocina");
        jButton2.setBorder(null);
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.setFocusPainted(false);
        jButton2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 210, 60));

        jButton3.setBackground(new java.awt.Color(51, 56, 59));
        jButton3.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ic3.png"))); // NOI18N
        jButton3.setText("      Factura");
        jButton3.setBorder(null);
        jButton3.setBorderPainted(false);
        jButton3.setContentAreaFilled(false);
        jButton3.setFocusPainted(false);
        jButton3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, 210, 60));

        CamareroButton.setBackground(new java.awt.Color(51, 56, 59));
        CamareroButton.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        CamareroButton.setForeground(new java.awt.Color(255, 255, 255));
        CamareroButton.setBorder(null);
        CamareroButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ic1.png"))); // NOI18N
        CamareroButton.setText("      Tomar pedidos");
        CamareroButton.setBorder(null);
        CamareroButton.setBorderPainted(false);
        CamareroButton.setContentAreaFilled(false);
        CamareroButton.setFocusPainted(false);
        CamareroButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        CamareroButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CamareroButtonActionPerformed(evt);
            }
        });
        jPanel1.add(CamareroButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 210, 60));

        jButton4.setBackground(new java.awt.Color(51, 56, 59));
        jButton4.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ic4.png"))); // NOI18N
        jButton4.setText("      Fin del dia");
        jButton4.setBorder(null);
        jButton4.setBorderPainted(false);
        jButton4.setContentAreaFilled(false);
        jButton4.setFocusPainted(false);
        jButton4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 460, 210, 60));

        bg.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 720));

        head.setBackground(new java.awt.Color(255, 255, 255));
        head.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                headMouseDragged(evt);
            }
        });
        head.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                headMousePressed(evt);
            }
        });
        head.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        title1.setBackground(new java.awt.Color(140, 22, 25));
        title1.setFont(new java.awt.Font("Roboto Medium", 1, 18)); // NOI18N
        title1.setForeground(new java.awt.Color(140, 22, 25));
        title1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title1.setText("Restaurante Minitas");
        jPanel2.add(title1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 0, 790, 80));

        tx1.setBackground(new java.awt.Color(0, 0, 0));
        tx1.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        tx1.setForeground(new java.awt.Color(88, 20, 11));
        tx1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tx1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tx1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tx1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tx1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tx1MouseExited(evt);
            }
        });
        jPanel2.add(tx1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 24, 15, 15));

        b1.setBackground(new java.awt.Color(255, 0, 51));
        b1.setForeground(new java.awt.Color(255, 102, 51));
        b1.setToolTipText("cerrar");
        b1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        b1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        b1.setPreferredSize(new java.awt.Dimension(20, 20));
        b1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b1MouseClicked(evt);
            }
        });
        b1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(b1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 25, 15, 15));

        tx2.setBackground(new java.awt.Color(0, 0, 0));
        tx2.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        tx2.setForeground(new java.awt.Color(173, 109, 32));
        tx2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tx2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tx2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tx2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tx2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tx2MouseExited(evt);
            }
        });
        jPanel2.add(tx2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1215, 23, 15, 15));

        b2.setBackground(new java.awt.Color(255, 255, 0));
        b2.setForeground(new java.awt.Color(255, 255, 0));
        b2.setToolTipText("miminizar");
        b2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        b2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        b2.setPreferredSize(new java.awt.Dimension(20, 20));
        b2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout b2Layout = new javax.swing.GroupLayout(b2);
        b2.setLayout(b2Layout);
        b2Layout.setHorizontalGroup(
            b2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 15, Short.MAX_VALUE)
        );
        b2Layout.setVerticalGroup(
            b2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 15, Short.MAX_VALUE)
        );

        jPanel2.add(b2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1215, 25, 15, 15));

        tx3.setBackground(new java.awt.Color(0, 0, 0));
        tx3.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        tx3.setForeground(new java.awt.Color(47, 104, 8));
        tx3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tx3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tx3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tx3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tx3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tx3MouseExited(evt);
            }
        });
        jPanel2.add(tx3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 24, 15, 15));

        b3.setBackground(new java.awt.Color(0, 204, 0));
        b3.setForeground(new java.awt.Color(28, 191, 48));
        b3.setToolTipText("maximizar");
        b3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        b3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        b3.setPreferredSize(new java.awt.Dimension(20, 20));
        b3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout b3Layout = new javax.swing.GroupLayout(b3);
        b3.setLayout(b3Layout);
        b3Layout.setHorizontalGroup(
            b3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 15, Short.MAX_VALUE)
        );
        b3Layout.setVerticalGroup(
            b3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 15, Short.MAX_VALUE)
        );

        jPanel2.add(b3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 25, 15, 15));

        dark.setBorder(null);
        dark.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                darkActionPerformed(evt);
            }
        });
        jPanel2.add(dark, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 20, -1, -1));

        head.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 80));

        bg.add(head, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 80));

        jSeparator1.setBackground(new java.awt.Color(140, 22, 25));
        jSeparator1.setForeground(new java.awt.Color(140, 22, 25));
        bg.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 80, 930, 50));

        bgc.setBackground(new java.awt.Color(255, 255, 255));
        bgc.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/u.png"))); // NOI18N
        bgc.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1050, 640));

        bg.add(bgc, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 80, 1050, 640));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
            Mesa_Info mesaInfo = new Mesa_Info(Controlador);
            mesaInfo.setVisible(true);
        } catch (IOException ex) {
            Logger.getLogger(MenuPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jButton3ActionPerformed

    private void CamareroButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CamareroButtonActionPerformed

        DefaultTableModel dm = (DefaultTableModel) TomarPedidos.InfoTable.getModel();

        for (int i = TomarPedidos.InfoTable.getRowCount() - 1; i >= 0; i--) {
            dm.removeRow(i);
        }

        DefaultTableModel platos = (DefaultTableModel) TomarPedidos.PlatosTable.getModel();
        DefaultTableModel bebidas = (DefaultTableModel) TomarPedidos.BebidasTable.getModel();
        DefaultTableModel postres = (DefaultTableModel) TomarPedidos.PostresTable.getModel();

        for (int i = TomarPedidos.BebidasTable.getRowCount() - 1; i >= 0; i--) {
            bebidas.removeRow(i);
        }

        for (int i = TomarPedidos.PlatosTable.getRowCount() - 1; i >= 0; i--) {
            platos.removeRow(i);
        }

        for (int i = TomarPedidos.PostresTable.getRowCount() - 1; i >= 0; i--) {
            postres.removeRow(i);
        }

        Controlador.AgregarEnMenu(platos, bebidas, postres);

        TomarPedidos.setVisible(true);

    }//GEN-LAST:event_CamareroButtonActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        cocina.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
try{
        DefaultTableModel model = (DefaultTableModel) FinDelDia.FinMesaTable.getModel();
        Controlador.FinDia(FinDelDia.VentasLabel, FinDelDia.PlatoLabel, FinDelDia.CamareroLabel, model,
                FinDelDia.MenosVendidoLabel, FinDelDia.AliLabel);

        FinDelDia.setVisible(true);
}
catch(Exception ex){
}


    }//GEN-LAST:event_jButton4ActionPerformed

    private void tx1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tx1MouseClicked
        System.exit(0);
    }//GEN-LAST:event_tx1MouseClicked

    private void tx1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tx1MouseEntered
        tx1.setText("×");
        tx1.setBackground(new Color(0,0,0,0));
    }//GEN-LAST:event_tx1MouseEntered

    private void tx1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tx1MouseExited
        tx1.setText("");
        tx1.setBackground(new Color(0,0,0,0));
    }//GEN-LAST:event_tx1MouseExited

    private void b1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b1MouseClicked

    }//GEN-LAST:event_b1MouseClicked

    private void tx2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tx2MouseClicked
        this.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_tx2MouseClicked

    private void tx2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tx2MouseEntered
        tx2.setText("-");
        tx2.setBackground(new Color(0,0,0,0));
    }//GEN-LAST:event_tx2MouseEntered

    private void tx2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tx2MouseExited
        tx2.setText("");
        tx2.setBackground(new Color(0,0,0,0));
    }//GEN-LAST:event_tx2MouseExited

    private void b2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b2MouseClicked

    }//GEN-LAST:event_b2MouseClicked

    private void tx3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tx3MouseClicked

    }//GEN-LAST:event_tx3MouseClicked

    private void tx3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tx3MouseEntered
        tx3.setText("+");
        tx3.setBackground(new Color(0,0,0,0));
    }//GEN-LAST:event_tx3MouseEntered

    private void tx3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tx3MouseExited
        tx3.setText("");
        tx3.setBackground(new Color(0,0,0,0));
    }//GEN-LAST:event_tx3MouseExited

    private void b3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b3MouseClicked

    }//GEN-LAST:event_b3MouseClicked

    private void darkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_darkActionPerformed
        //Cambiamos los colores del fondo
        boolean darkmode= false;
        if(!darkmode){
            title1.setForeground(new Color(168,168,168));
            dark.setIcon(new ImageIcon(getClass().getResource("/codigo/darkmode_2.png")));
            darkmode=true;
        }else{
            title1.setForeground(new Color(102,102,102));
            dark.setIcon(new ImageIcon(getClass().getResource("/codigo/darkmode_1.png")));
            darkmode=false;
        }

    }//GEN-LAST:event_darkActionPerformed

    private void headMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x- xMouse, y- yMouse);
    }//GEN-LAST:event_headMouseDragged

    private void headMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headMousePressed
        xMouse= evt.getX();
        yMouse= evt.getY();
    }//GEN-LAST:event_headMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                try {
                    new MenuPrincipal().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(MenuPrincipal.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CamareroButton;
    private javax.swing.JPanel b1;
    private javax.swing.JPanel b2;
    private javax.swing.JPanel b3;
    private javax.swing.JPanel bg;
    private javax.swing.JPanel bgc;
    private javax.swing.JButton dark;
    private javax.swing.JPanel head;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel title1;
    private javax.swing.JLabel tx1;
    private javax.swing.JLabel tx2;
    private javax.swing.JLabel tx3;
    // End of variables declaration//GEN-END:variables
    class RoundedPanel extends JPanel
    {
        private Color backgroundColor;
        private int cornerRadius = 15;
        public RoundedPanel(LayoutManager layout, int radius) {
            super(layout);
            cornerRadius = radius;
        }
        public RoundedPanel(LayoutManager layout, int radius, Color bgColor) {
            super(layout);
            cornerRadius = radius;
            backgroundColor = bgColor;
        }
        public RoundedPanel(int radius) {
            super();
            cornerRadius = radius;
            
        }
        public RoundedPanel(int radius, Color bgColor) {
            super();
            cornerRadius = radius;
            backgroundColor = bgColor;
        }
        @Override
        protected void paintComponent(Graphics g) {
            super.paintComponent(g);
            Dimension arcs = new Dimension(cornerRadius, cornerRadius);
            int width = getWidth();
            int height = getHeight();
            Graphics2D graphics = (Graphics2D) g;
            graphics.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
            //Draws the rounded panel with borders.
            if (backgroundColor != null) {
                graphics.setColor(backgroundColor);
            } else {
                graphics.setColor(getBackground());
            }
            graphics.fillRoundRect(0, 0, width-1, height-1, arcs.width, arcs.height); //paint background
            graphics.setColor(getForeground());
//            graphics.drawRoundRect(0, 0, width-1, height-1, arcs.width, arcs.height); //paint border
//             
        }
    }
}
